### PR TITLE
Twap integration

### PR DESCRIPTION
**Pull request by professionallyatortoise**
Motivation:

Price feeds are critical for letting others build derivatives, integrating the TWAP into the pool creates incentives for builders to integrate into the pool, creating higher usage and demand for the pool. 

Implementation:
Create a rolling price history of the pool balance between swaps, at the start of the swap, append a price snapshot to the price history. I chose to do 5 rolling snapshots as it seemed like a good balance and based on historical usage there are around 5 txs every 5-15 minutes in the juno-axlusdc pool.

Using a query msg to expose the history allows builders to adjust how they would like to calculate the final price feed. Some may choose a simple avg, a time-weighted avg, or another scheme to best get an oracle.

Testing:
I created unit tests, showing its usefulness in a Flash Loan Attack, and how it would require more capital and time ( arb risks for attacker ), to successfully manipulate the oracle.

Additionally, I created a ts script that can deploy the contracts and demo the price feed. You may need to add a umockusdc to your LocalJuno genesis file to run it. I saw the deploy scripts are written in bash, but standard practice and ease of use says, a ts file makes more sense.

### CODE REVIEW

**Comment by verminator23** [comment]
Great work. This is a very important feature. A couple of comments
*  This deviates a bit from how TWAPs are typically done. The pair contract typically doesn’t store actual price feeds. It just reveals cumulative prices (weighted by time). Price feeds are implemented in a separate oracle contract that samples the cumulative prices at whatever interval.  
There’s only 3 things you really need in state: 
  1) price0_cumulative: sum of price0 * time_since_last_update
  2) price1_cumulative: sum of price1 * time_since_last_update
  3) timestamp: time of last update, needed to calculate 1 and 2

And all an oracle client has to do is sample the price0_cumulative or price1_cumulative at whatever time interval.

* In the current implementation, there’s no time weighted price accumulator at all really. So TWAP oracle clients can’t reliably sample the prices at custom time intervals. Imagine if there’s 5 swaps in 5 consecutive blocks, the max time granularity would be 1-5 blocks which is not ideal. This is why a generic accumulator should exist and the price feed logic should be implemented in a separate oracle contract.
*  You should probably call update_twap in add / remove liquidity handlers as well

Checkout: [Uniswap V2 ](https://github.com/Uniswap/v2-core/blob/ee547b17853e71ed4e0101ccfd52e70d5acded58/contracts/UniswapV2Pair.sol#L73)and [Astroport](https://github.com/astroport-fi/astroport-core/blob/1e1f480f56272d729d2ab10dc530ad12d8d0fb28/contracts/pair/src/contract.rs#L407) for examples

**Comment by professionallyatortoise** [comment]
Thanks!

I do agree that oracles are typically stored and maintained in a separate contract, but that adds an unnecessary and depending on the number of oracles + sample frequency,  creates an expensive upfront cost to anyone trying to build derivatives etc. In many cases, it is prohibitively expensive. Having the pool retain a memory adds some gas costs to swappers, but in return, it enables the infrastructure of derivatives and greatly expedites the speed of development. 

Without recreating Chainlink or Band, I do believe exposing the price feed with timestamps adds sufficient robustness and manipulation resistance. In the case of manipulation, one would have to do a bad trade, and maintain the trade there for at least 5 blocks (which is a parameter and 5 is just a starting place for discussion). In the world of arbs, 5 blocks is an eternity, and the attacker will likely be arb'd to death through an osmosis pool or other DEX. Crypto markets are generally efficient within themselves and there are people looking for arb opportunities between DEXs at all times often picking up only pennies, so I am not so worried about someone trying to take on that risk. 

In terms of why this approach, I was trying to let a protocol or any user decide how they create their oracle from the feed. In the integration test, I show one approach of forming a traditional TWAP @verminator23 , maybe the PR is misnambed and should be called price memory to enable TWAPs and other oracles ?

Lastly, I didn't add the update twap in the add and remove liquidity as they don't have a price impact as you are give / given a proportional amount of both

**Comment by verminator23** [comment]
I just don't think there's any way to actually use these price feeds securely. In UNI V2 oracles, you typically have to manipulate the price for an extended period of time e.g., 30 min / 1 hr, which is prohibitively expensive. In this case, you only have to manipulate the price for up to 5 blocks (~30 seconds).  And this lower bound on duration is effectively hardcoded and not configurable, since the pair contract has an explicit cap on how many price updates it stores. UNI V2 TWAP oracles allow you to have custom oracle durations pretty easily, since an accumulator is stored directly in the pair contract.

I guess if you just added the price accumulators this would support same features as UNI V2 TWAP oracles. But wouldn't recommend anyone use the price feeds stored here.

Do you have an examples of a system like this being used in any popular DEXes in production? And Chainlink price feeds don't count because they aggregate prices from various centralized exchanges based on volume (fundamentally different security assumptions / properties). The UNI V2 TWAP design is elegant and has been battle tested. We don't need to reinvent anything here.

**Comment by professionallyatortoise** [comment]
5 swaps is meant to be a starting place for discussion, so I wouldn't get hung up on 5 being insufficient, I agree, and 50 is probably overkill, so there likely exists a happy middle ground. the main ethos is to have the oracle price / price feed on the pool is to not increase the scope of projects that require oracles. Other 'popular' DEXs live in ecosystems that are much more mature and can rely on Link or Band to save the day, this is not the case for Juno as of writing, so there is less of a need for this type of development. 

And yes you can do it in a separate contract, but let's say you need a price accurate to the minute, you would need to update it 1x60x24x365x (gas fee) x (price of juno) x (number of oracles), I think we can see it's going to be prohibitively expensive to do so for small projects of which Juno is almost exclusively composed of. 

I can implement the uniswap design, but I mainly wanted to let protocols decide how they aggregate their prices instead of forcing a particular design. @verminator23 thoughts on this?

**Comment by mccallofthewild** [comment]
Yep @professionallyatortoise we really appreciate the PR but I 100% concur with @verminator23. The weighted average part of a TWAP is key to its resilience. 

We have already [ported the Astroport oracle to JunoSwap](https://github.com/notional-labs/UltraStableJuno/blob/3d5d64356799adf2422cf26c2203bc3892c2d4cd/contracts/junoswap-oracle/src/contract.rs) so your energies may be better spent reviewing/contributing there than reimplementing Uniswap.

**Comment by mccallofthewild** [comment]
Your concept of invoking the update _before_ the price changes is really interesting though. It completely removes the possibility for a sandwich attack and ensures the price used is always the the last price from the previous block. 

If we exclusively allowed the wasmswap contract to update the oracle, this could be a really solid design improvement.

**Comment by professionallyatortoise** [comment]
1. The TWAP can be built from the price history, you have the prices, you have times which means you have the twap, you can check the integration test for a sample implementation of building a twap based on these values. Though there's certainly an argument to be made for inefficiency, if there's a clear winner in twap implementations then just do it once instead of making each protocol come up with its own scheme.

2. Yes, if you do the current price you are going to be attacked much easier, so it is best to update the twap before any swapping occurs, or as you said 1 swap behind the actual price, requiring at least 1 arb opportunity 

3. And yes in terms of calling a separate oracle contract to update the price, yes, that's certainly possible, but _why_ not just have it all in one place where you are updating values on the contract itself instead of calling a separate contract? It seems like this is a missed opportunity, to bring more relevance to the pool as more teams will be incentived to hook into, instead of other DEXs like what loop is building for example. 

4. What are thoughts about porting your twap code into the pool contract itself so it's a uniswap / astroport style twap but built into the contract?

@verminator23 @mccallofthewild

**Comment by ezekiiel** [comment]
I am by no means an expert in price oracles, but it feels to me that we could solve this whole issue by just storing every historical price and time of that price in state. Then, anyone wanting a TWAP of whatever accuracy can just query for the time window they're interested in.

For example, in state we can store:

```rust
/// Maps (block_height, transaction_index) to the price _before_ that TX occured.
/// See: `env.transaction.index`.
pub const PRICE_HISTORY: Map<(u64, u32), PriceSnapshot> = Map::new("price_history")
```

Then, on every price change we can update this map. Now, to calculate the TWAP using the last ten blocks of price information. I can get the needed data with:

```rust
let iterator_over_snapshots = cw_storage_plus::range_with_prefix(deps.storage, PRICE_HISTORY.namespace(), Some(Bound::inclusive(height - 10).to_raw_bound(), None, Order::Ascending);
```

CosmWasm storage is prefixed, so you can get all the values belonging to a prefix in a gas efficient manner. We set our keys as `(height, index)` so that we can have more than one key at a given height, and still efficiently iterate over all the keys at a height. The alternative would be to store `Map(u64, Vec<PriceSnapshot>)` but this kills our time complexity because we have to load in a large vec for every height. By doing it this prefixed lookup we can outsource that heavy lifting to builtin CosmWasm database functions which should give us more favorable gas usage.

This should provide `O(number of prices you want)` performance, and we can pretty easily paginate this so that larger queries can be supported if needed.

**Comment by mccallofthewild** [comment]
@ezekiiel every block is fine. We don't have a usecase for the price at every swap. As is, the range query would run out of gas if there were hundreds of swaps in the past 10 blocks. And we can index both height and timestamp with a MultiIndex.

**Comment by mccallofthewild** [comment]
@professionallyatortoise twap *can* be built from price history. But the idea is that the price updates slowly over time to accurately indicate general market sentiment. If we look at prices over the course of a day stored at every block, it's around 14k records.

**Comment by mccallofthewild** [comment]
> why not just have it all in one place where you are updating values on the contract itself instead of calling a separate contract?

I err on the side of conservative bytecodes. I'll leave it up to the junoswap team.

**Comment by professionallyatortoise** [comment]
> @professionallyatortoise twap _can_ be built from price history. But the idea is that the price updates slowly over time to accurately indicate general market sentiment. If we look at prices over the course of a day stored at every block, it's around 14k records.

I'm not so sure about a snapshot of every swap, it seems a bit like overkill with values becoming irrelevant very quickly, I also believe there's a contract size limit not sure if that includes storage (but something to consider), which is why I was a fan of a rolling price history. 

> > why not just have it all in one place where you are updating values on the contract itself instead of calling a separate contract?
> 
> I err on the side of conservative bytecodes. I'll leave it up to the junoswap team.

In your design, you have to actively maintain that price feed, a slip execution or internet loss or something could cause you to have a stale price having many downstream affects (such as bad liquidations, bad debt, etc), in this design you don't run into such a problem, the price feed is gathered and stored in-contract requiring no 3rd party. I am leaning towards the price accumulator or price history, but on-contract

Anyone on the wasmswap team want to chime in?

**Comment by mccallofthewild** [comment]
The size limit is the bytecode size limit I referred to above. That's why it's generally unwise to cram two contracts into one.

> In your design...

The TWAP would be updated on-chain before the swap. Directly or in a `prehook`. Once per block. There is no third party.

**Comment by mccallofthewild** [comment]
@ben2x4 The goal here is to make a junoswap oracle. Would you prefer the oracle in the AMM or in a separate contract?

**Comment by professionallyatortoise** [comment]
> The size limit is the bytecode size limit I referred to above. That's why it's generally unwise to cram two contracts into one.
> 
> > In your design...
> 
> The TWAP would be updated on-chain before the swap. Directly or in a response message. Once per block. There is no third party.

Not sure how my proposal is 'cramming' two contracts in one...when it's a simple operation... saving a few data points doesn't need to be its own contract...Also, your suggestion would introducing an outside dependency to the wasmswap contract by broadcasting it directly, which in my opinion is far from ideal, maintaining 2 contracts, initializing it from the start, adding dependencies to your contract interface etc. The AMM should be all-inclusive and not be making unnecessary outbound execute msgs

**Comment by ben2x4** [comment]
Wow, ton of discussion here! Will dig through this tomorrow!

**Comment by ezekiiel** [comment]
> @mccallofthewild The size limit is the bytecode size limit I referred to above

FWIW - I asked about this in the CosmWasm Discord. I think we are unlikely to hit any issues here. From the discord:

> The size of the map doesn't matter. There's a cost per-read and a cost per-byte. There's also a cost per-iteration but it's not clear to me if that's in addition or in place of the read cost.

My read is that storing a price value at every block there is a transaction would be fine. IMO this is a pretty simple contract change and could significantly reduce the cost of using Junoswap as an oracle as there is no need to pay TX fees to update an external contract. Will defer to @ben2x4's wisdom here though. :)

As an aside, if we're worried about increased fees for users swapping we've been doing a lot of thinking about gas costs at DAO DAO. The general conclusion has tended to be that gas costs from CosmWasm execution are generally dwarfed by other ones related to submitting a TX. We're working on a way to test gas usage and we could use that here to compare before and after swap prices if we're particularly concerned: https://github.com/DA0-DA0/dao-contracts/pull/410

**Comment by mccallofthewild** [comment]
> @ezekiiel We're working on a way to test gas usage

This is awesome 🔥 

I'm not opposed to the price history idea. But before moving forward we should have a consensus on how it can be converted into a manipulation-resistant oracle.

**Pull request closed without merging**
